apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_9b5b81b53155
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SECRET_LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  name: loglevel-secret
                  key: loglevel
            - name: SECRET_MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-db
                  key: database
            - name: SECRET_MONGO_DB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-db
                  key: uri
