apiVersion: apps/v1
kind: Deployment
spec:
    template:
        metadata:
            name: default
            labels:
                app: backend
        spec:
            containers:
                - name: backend
                  # 여러분의 image 주소를 입력해주세요.
                  image: krmp-d2hub-idock.9rum.cc/dev-test/repo_941daa778d83:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
