apiVersion: apps/v1
kind: Deployment
metadata:
  name: ultimatetodo
spec:
  replicas: 1  # 필요한 수로 변경하세요
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: ultimatetodo
    spec:
      containers:
        - name: backend
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_d144b3216ea4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
